spring.application.name=Interdisciplinar

# Configuracao do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_db
spring.datasource.username=postgres
spring.datasource.password=postdba

# Atualizar as tabelas do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Nao formatar os comandos SQL no console
spring.jpa.properties.hibernate.format_sql=false

# Mostrar os comandos SQL no console
spring.jpa.show-sql=true

server.port=8080